[package]
name = "rustybgpd"
version = "0.2.0"
authors = ["FUJITA Tomonori <fujita.tomonori@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1"
tonic = "0.12.3"
bytes = "1.0"
chrono = "0.4"
prost = "0.13.3"
prost-types = "0.13.3"
prost-derive = "0.13.3"
tokio = { version = "=1.41", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec","time"] }
tokio-stream = { version = "0.1", features = ["net"] }
clap = "4.5"
futures = "=0.3.31"
futures-core = "=0.3.31"
patricia_tree = "0.8"
regex = "1"
hostname = "0.4"
fnv = "1.0"
num_cpus = "1.0"
socket2 = { version = "0.5", features = ["all"]}
byteorder = "1.3.2"
once_cell = "1"
thiserror = "1"
libc = "0.2.94"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.8.19"
nix = { version = "0.29", features = ["socket"] }
uuid = { version = "1.11", features = ["v4"] }
ip_network_table-deps-treebitmap = "0.5.0"

[build-dependencies]
tonic-build = "0.12.3"
protobuf-src = "2.1.0"
